### ISSUE TITLE
epic_id and labels fields (also v2 API?)

### ISSUE THREAD

**Issue by traycerb** [mikkelson/clubhouse-csv-import#4]
Not sure if this is being updated, but I had trouble getting the `epic_id` and `labels` to work.  maybe because its deprecated v1 api?

Also, some fields require data, like the owner UUID, which i can't seem to determine from the export functions, as they have been upgraded to v2 and don't expose that information.

Is there any chance of updating this for v2?  I could help with documentation, but unfortunately, coding-wise it's beyond my scope of knowledge.

**Comment by mikkelson** [comment]
@traycerb Thanks for your feedback, this has now jumped to API V3.
