### ISSUE TITLE
Does not work with direct download of Clubhouse CSV file

### ISSUE THREAD

**Issue by ohmegasquared** [mikkelson/clubhouse-csv-import#5]
I tried using the tool and got errors for `Line N is missing required field project_id, name or story_type`, when they all have those fields. I used a CSV downloaded from Clubhouse and could not upload with the tool.

**Comment by mikkelson** [comment]
Hi @ohmegasquared.

I was able to import using the example csv in the repo....

![image](https://user-images.githubusercontent.com/5843723/57986646-71294780-7a6f-11e9-8618-9b6ee4bd77c7.png)

Can you please attach a sample CSV that are you having trouble with, please? So I can replicate your issue.

**Comment by ohmegasquared** [comment]
Here is a sample file! Thanks for looking into it! 

[debug.txt](https://github.com/mikkelson/clubhouse-csv-import/files/3195613/debug.txt)

**Comment by mikkelson** [comment]
@ohmegasquared I can see that there are many line breaks in this field, but not every field is enclosed.

For example, from 5:

`[ ] c

[ ] d",On Deck,7676,XYZ,D,-5:00:00

7545,name 3,feature,76828`

You can see the line is broken.

To fix this, either enclose your fields or remove the line breaks.
